# app/seeds/subgroups.toml

[liella.all_songs]
name = "All Songs"
is_custom = false
songs = [
    "始まりは君の空",
    "Dancing Heart La-Pa-Pa-Pa!",
    "Dreaming Energy",
    "私のSymphony",
    "START!! True dreams",
    "だから僕らは鳴らすんだ！",
    "未来は風のように",
    "この街でいまキミと",
    "未来予報ハレルヤ！",
    "Tiny Stars",
    "GOING UP",
    "1.2.3！",
    "心キラララ",
    "常夏☆サンシャイン",
    "Wish Song",
    "バイバイしちゃえば！？",
    "瞬きの先へ",
    "ノンフィクション!!",
    "Starlight Prologue",
    "Day1",
    "Dream Rainbow",
    "Primary",
    "Memories",
    "Anniversary",
    "Message",
    "Ringing!",
    "Oh！レディ・ステディ・ポジティブ",
    "Dears",
    "Departure",
    "ほんのちょっぴり",
    "だいすきのうた",
    "グソクムシのうた",
    "Shooting Voice!!",
    "勇気のカケラ",
    "ヒロインズ☆ランウェイ",
    "リバーブ",
    "HOT PASSION!!",
    "Till Sunrise",
    "探して！Future",
    "クレッシェンドゆ・ら",
    "HAPPY TO DO WA！",
    "Stella!",
    "変わらないすべて",
    "トゥ トゥ トゥ！",
    "What a Wonderful Dream!!",
    "青空を待ってる",
    "水色のSunday",
    "Flyer's High",
    "みてろ！",
    "微熱のワルツ",
    "ユニゾン",
    "WE WILL!!",
    "スター宣言",
    "追いかける夢の先で",
    "水しぶきのサイン",
    "Welcome to 僕らのセカイ",
    "Go!! リスタート",
    "色づいて透明",
    "揺らぐわ",
    "ビタミンSUMMER！",
    "Chance Day, Chance Way！",
    "ユートピアマジック",
    "POP TALKING",
    "Sing！Shine！Smile！",
    "未来の音が聴こえる",
    "TO BE CONTINUED",
    "名前呼びあうように",
    "Dreamer Coaster",
    "Butterfly Wing",
    "エンドレスサーキット",
    "迷宮讃歌",
    "プライム・アドベンチャー",
    "パレードはいつも",
    "エーデルシュタイン",
    "駆けるメリーゴーランド",
    "Time to go",
    "Hoshizora Monologue",
    "Blooming Dance！Dance！",
    "Including you",
    "Second Sparkle",
    "ビギナーズRock!!",
    "ミッドナイトラプソディ",
    "星屑クルージング",
    "君を想う花になる",
    "茜心",
    "ガラスボールリジェクション",
    "Eyeをちょうだい",
    "Starry Prayer",
    "Free Flight",
    "MIRACLE NEW STORY",
    "キラーキューン☆",
    "UNIVERSE!!",
    "Jump Into the New World",
    "オルタネイト",
    "ベロア",
    "Dancing Raspberry",
    "影遊び",
    "不可視なブルー",
    "A Little Love",
    "シェキラ☆☆☆",
    "FANTASTiC",
    "ディストーション",
    "ニュートラル",
    "Jellyfish",
    "全力ライオット",
    "カメリアの囁き",
    "Thank you Good morning",
    "アイコトバ！",
    "Let's be ONE",
    "DAISUKI FULL POWER",
    "青春HOPPERS",
    "Within a Dream",
    "Bubble Rise",
    "Special Color",
    "いつものピースサイン",
    "ファイティングコール",
    "絶対的LOVER",
    "Dazzling Game",
    "QUESTION99",
    "真っ赤。",
    "笑顔のPromise",
    "スーパースター!!",
    "君・街・空・星",
    "dolce",
    "Summer Escape!!",
    "11th moon",
    "ひとひらだけ",
    "結ぶメロディ",
    "あふれる言葉",
    "罪DA・YO・NE",
    "想われマリオネット",
    "ティーンエイジ・ロンリネス",
    "Over Over",
    "Sky Linker",
    "LiLiA",
    "てくてく日和",
    "ワイルドカード",
    "ファンダメンタル",
    "Just woo!!",
    "パステルコラージュ",
    "結び葉",
    "ルカ",
    "Rhythm",
    "Aspire",
    "オレンジのままで",
    "High！モチベーション",
    "OPEN THE G☆TE!!!"
]

[liella.solos]
name = "Solos"
is_custom = false
songs = [
    "LiLiA",
    "茜心",
    "ガラスボールリジェクション",
    "ファンダメンタル",
    "Eyeをちょうだい",
    "ワイルドカード",
    "Oh！レディ・ステディ・ポジティブ",
    "結び葉",
    "エーデルシュタイン",
    "ルカ",
    "Rhythm",
    "ヒロインズ☆ランウェイ",
    "みてろ！",
    "微熱のワルツ",
    "ほんのちょっぴり",
    "てくてく日和",
    "dolce",
    "結ぶメロディ",
    "11th moon",
    "ひとひらだけ",
    "Primary",
    "Memories",
    "Anniversary",
    "Message",
    "Ringing!",
    "勇気のカケラ",
    "Flyer's High",
    "Free Flight",
    "Over Over",
    "Sky Linker",
    "Dears",
    "Starry Prayer",
    "Just woo!!",
    "Hoshizora Monologue",
    "グソクムシのうた",
    "ティーンエイジ・ロンリネス",
    "ノンフィクション!!",
    "Departure"
]

[liella.group_songs]
name = "Group Songs"
is_custom = false
songs = [
    "Starlight Prologue",
    "Aspire",
    "Dazzling Game",
    "真っ赤。",
    "始まりは君の空",
    "未来は風のように",
    "ビタミンSUMMER！",
    "Bubble Rise",
    "いつものピースサイン",
    "ノンフィクション!!",
    "Second Sparkle",
    "Special Color",
    "私のSymphony",
    "キラーキューン☆",
    "Tiny Stars",
    "スーパースター!!",
    "START!! True dreams",
    "Wish Song",
    "QUESTION99",
    "OPEN THE G☆TE!!!",
    "揺らぐわ",
    "絶対的LOVER",
    "What a Wonderful Dream!!",
    "常夏☆サンシャイン",
    "Day1",
    "未来予報ハレルヤ！",
    "だから僕らは鳴らすんだ！",
    "Chance Day, Chance Way！",
    "笑顔のPromise",
    "アイコトバ！",
    "WE WILL!!",
    "DAISUKI FULL POWER",
    "シェキラ☆☆☆",
    "Jump Into the New World",
    "UNIVERSE!!",
    "MIRACLE NEW STORY",
    "オレンジのままで",
    "結ぶメロディ",
    "追いかける夢の先で",
    "君・街・空・星",
    "Dream Rainbow",
    "Let's be ONE",
    "探して！Future",
    "FANTASTiC",
    "Shooting Voice!!",
    "ユニゾン",
    "TO BE CONTINUED",
    "1.2.3！",
    "Welcome to 僕らのセカイ",
    "青春HOPPERS",
    "POP TALKING",
    "ファイティングコール",
    "バイバイしちゃえば！？",
    "スター宣言",
    "未来の音が聴こえる",
    "この街でいまキミと",
    "瞬きの先へ",
    "Sing！Shine！Smile！",
    "Go!! リスタート",
    "名前呼びあうように",
    "Dancing Heart La-Pa-Pa-Pa!",
    "水しぶきのサイン",
    "Dreaming Energy",
    "GOING UP",
    "Primary",
    "Within a Dream",
    "Including you",
    "色づいて透明",
    "ユートピアマジック",
    "Departure",
    "プライム・アドベンチャー",
    "トゥ トゥ トゥ！",
    "Time to go"
]

[liella.liella_no_uta]
name = "Liella no Uta"
is_custom = false
songs = [
    "結ぶメロディ",
    "11th moon",
    "Primary",
    "Summer Escape!!",
    "迷宮讃歌",
    "dolce",
    "Anniversary",
    "Departure",
    "Dears",
    "ひとひらだけ",
    "エンドレスサーキット",
    "パレードはいつも",
    "Message",
    "Ringing!",
    "プライム・アドベンチャー",
    "駆けるメリーゴーランド",
    "Memories",
    "Dreamer Coaster",
    "Time to go"
]

[liella.season_1_singles]
name = "Season 1 Singles"
is_custom = false
songs = [
    "START!! True dreams",
    "だから僕らは鳴らすんだ！",
    "未来は風のように",
    "この街でいまキミと",
    "未来予報ハレルヤ！",
    "Tiny Stars",
    "GOING UP",
    "1.2.3！",
    "常夏☆サンシャイン",
    "Wish Song",
    "バイバイしちゃえば！？",
    "瞬きの先へ",
    "ノンフィクション!!",
    "Day1",
    "Dream Rainbow",
    "Starlight Prologue"
]

[liella.season_2_singles]
name = "Season 2 Singles"
is_custom = false
songs = [
    "WE WILL!!",
    "スター宣言",
    "追いかける夢の先で",
    "水しぶきのサイン",
    "Welcome to 僕らのセカイ",
    "Go!! リスタート",
    "色づいて透明",
    "揺らぐわ",
    "ビタミンSUMMER！",
    "Chance Day, Chance Way！",
    "ユートピアマジック",
    "POP TALKING",
    "Sing！Shine！Smile！",
    "未来の音が聴こえる",
    "TO BE CONTINUED",
    "名前呼びあうように",
    "Butterfly Wing",
    "エーデルシュタイン"
]

[liella.season_3_singles]
name = "Season 3 Singles"
is_custom = false
songs = [
    "Let's be ONE",
    "DAISUKI FULL POWER",
    "青春HOPPERS",
    "Within a Dream",
    "Bubble Rise",
    "Special Color",
    "いつものピースサイン",
    "ファイティングコール",
    "絶対的LOVER",
    "Dazzling Game",
    "QUESTION99",
    "真っ赤。",
    "笑顔のPromise",
    "スーパースター!!",
    "君・街・空・星"
]

[liella.catchu]
name = "CatChu!"
is_custom = false
is_subunit = true
songs = [
    "オルタネイト",
    "影遊び",
    "ディストーション",
    "全力ライオット"
]

[liella.kaleidoscore]
name = "KALEIDOSCORE"
is_custom = false
is_subunit = true
songs = [
    "ベロア",
    "不可視なブルー",
    "ニュートラル",
    "カメリアの囁き"
]

[liella.5syncri5e]
name = "5syncri5e!"
is_custom = false
is_subunit = true
songs = [
    "Dancing Raspberry",
    "A Little Love",
    "Jellyfish",
    "Thank you Good morning"
]

# Example of potential user-defined custom subgroup
# [liella.custom_subgroups.user_top_10]
# name = "User's Top 10"l
# is_custom = true
# creator = "admin"
# songs = [
#     "Starlight Prologue",
#     "Aspire",
#     "Dazzling Game",
#     "真っ赤。",
#     "始まりは君の空",
#     "LiLiA",
#     "Starry Prayer",
#     "Free Flight",
#     "絶対的LOVER",
#     "Aspire"
# ]