# app/seeds/subgroups.toml

[liella.all_songs]
name = "All Songs"
is_custom = false
songs = [
    "始まりは君の空",
    "Dancing Heart La-Pa-Pa-Pa!",
    "Dreaming Energy",
    "私のSymphony",
    "START!! True dreams",
    "だから僕らは鳴らすんだ！",
    "未来は風のように",
    "この街でいまキミと",
    "未来予報ハレルヤ！",
    "Tiny Stars",
    "GOING UP",
    "1.2.3！",
    "心キラララ",
    "常夏☆サンシャイン",
    "Wish Song",
    "バイバイしちゃえば！？",
    "瞬きの先へ",
    "ノンフィクション!!",
    "Starlight Prologue",
    "Day1",
    "Dream Rainbow",
    "Primary",
    "Memories",
    "Anniversary",
    "Message",
    "Ringing!",
    "Oh！レディ・ステディ・ポジティブ",
    "Dears",
    "Departure",
    "ほんのちょっぴり",
    "だいすきのうた",
    "グソクムシのうた",
    "Shooting Voice!!",
    "勇気のカケラ",
    "ヒロインズ☆ランウェイ",
    "リバーブ",
    "HOT PASSION!!",
    "Till Sunrise",
    "探して！Future",
    "クレッシェンドゆ・ら",
    "HAPPY TO DO WA！",
    "Stella!",
    "変わらないすべて",
    "トゥ トゥ トゥ！",
    "What a Wonderful Dream!!",
    "青空を待ってる",
    "水色のSunday",
    "Flyer's High",
    "みてろ！",
    "微熱のワルツ",
    "ユニゾン",
    "WE WILL!!",
    "スター宣言",
    "追いかける夢の先で",
    "水しぶきのサイン",
    "Welcome to 僕らのセカイ",
    "Go!! リスタート",
    "色づいて透明",
    "揺らぐわ",
    "ビタミンSUMMER！",
    "Chance Day, Chance Way！",
    "ユートピアマジック",
    "POP TALKING",
    "Sing！Shine！Smile！",
    "未来の音が聴こえる",
    "TO BE CONTINUED",
    "名前呼びあうように",
    "Dreamer Coaster",
    "Butterfly Wing",
    "エンドレスサーキット",
    "迷宮讃歌",
    "プライム・アドベンチャー",
    "パレードはいつも",
    "エーデルシュタイン",
    "駆けるメリーゴーランド",
    "Time to go",
    "Hoshizora Monologue",
    "Blooming Dance！Dance！",
    "Including you",
    "Second Sparkle",
    "ビギナーズRock!!",
    "ミッドナイトラプソディ",
    "星屑クルージング",
    "君を想う花になる",
    "茜心",
    "ガラスボールリジェクション",
    "Eyeをちょうだい",
    "Starry Prayer",
    "Free Flight",
    "MIRACLE NEW STORY",
    "キラーキューン☆",
    "UNIVERSE!!",
    "Jump Into the New World",
    "オルタネイト",
    "ベロア",
    "Dancing Raspberry",
    "影遊び",
    "不可視なブルー",
    "A Little Love",
    "シェキラ☆☆☆",
    "FANTASTiC",
    "ディストーション",
    "ニュートラル",
    "Jellyfish",
    "全力ライオット",
    "カメリアの囁き",
    "Thank you Good morning",
    "アイコトバ！",
    "Let's be ONE",
    "DAISUKI FULL POWER",
    "青春HOPPERS",
    "Within a Dream",
    "Bubble Rise",
    "Special Color",
    "いつものピースサイン",
    "ファイティングコール",
    "絶対的LOVER",
    "Dazzling Game",
    "QUESTION99",
    "真っ赤。",
    "笑顔のPromise",
    "スーパースター!!",
    "君・街・空・星",
    "dolce",
    "Summer Escape!!",
    "11th moon",
    "ひとひらだけ",
    "結ぶメロディ",
    "あふれる言葉",
    "罪DA・YO・NE",
    "想われマリオネット",
    "ティーンエイジ・ロンリネス",
    "Over Over",
    "Sky Linker",
    "LiLiA",
    "てくてく日和",
    "ワイルドカード",
    "ファンダメンタル",
    "Just woo!!",
    "パステルコラージュ",
    "結び葉",
    "ルカ",
    "Rhythm",
    "Aspire",
    "オレンジのままで",
    "High！モチベーション",
    "OPEN THE G☆TE!!!"
]

[liella.solos]
name = "Solos"
is_custom = false
songs = [
    "LiLiA",
    "茜心",
    "ガラスボールリジェクション",
    "ファンダメンタル",
    "Eyeをちょうだい",
    "ワイルドカード",
    "Oh！レディ・ステディ・ポジティブ",
    "結び葉",
    "エーデルシュタイン",
    "ルカ",
    "Rhythm",
    "ヒロインズ☆ランウェイ",
    "みてろ！",
    "微熱のワルツ",
    "ほんのちょっぴり",
    "てくてく日和",
    "dolce",
    "結ぶメロディ",
    "11th moon",
    "ひとひらだけ",
    "Primary",
    "Memories",
    "Anniversary",
    "Message",
    "Ringing!",
    "勇気のカケラ",
    "Flyer's High",
    "Free Flight",
    "Over Over",
    "Sky Linker",
    "Dears",
    "Starry Prayer",
    "Just woo!!",
    "Hoshizora Monologue",
    "グソクムシのうた",
    "ティーンエイジ・ロンリネス",
    "ノンフィクション!!",
    "Departure"
]

[liella.subunits]
name = "Subunits"
is_custom = false
songs = [
    "オルタネイト",
    "ベロア",
    "不可視なブルー",
    "ニュートラル",
    "カメリアの囁き",
    "ディストーション",
    "全力ライオット",
    "影遊び",
    "Dancing Raspberry",
    "Thank you Good morning",
    "A Little Love",
    "Jellyfish"
]

[liella.group_songs]
name = "Group Songs"
is_custom = false
songs = [
    "WE WILL!!",
    "スター宣言",
    "追いかける夢の先で",
    "水しぶきのサイン",
    "Welcome to 僕らのセカイ",
    "色づいて透明",
    "揺らぐわ",
    "ビタミンSUMMER！",
    "Chance Day, Chance Way！",
    "ユートピアマジック",
    "POP TALKING",
    "Sing！Shine！Smile！",
    "未来の音が聴こえる",
    "TO BE CONTINUED",
    "名前呼びあうように",
    "Butterfly Wing",
    "エンドレスサーキット",
    "迷宮讃歌",
    "プライム・アドベンチャー",
    "パレードはいつも",
    "駆けるメリーゴーランド",
    "Time to go",
    "Second Sparkle",
    "ビギナーズRock!!",
    "ミッドナイトラプソディ",
    "星屑クルージング",
    "君を想う花になる",
    "ガラスボールリジェクション",
    "心キラララ",
    "常夏☆サンシャイン",
    "Wish Song",
    "バイバイしちゃえば！？",
    "瞬きの先へ",
    "青空を待ってる",
    "水色のSunday",
    "あふれる言葉"
]

[liella.liella_no_uta]
name = "Liella no Uta"
is_custom = false
songs = [
    "結ぶメロディ",
    "11th moon",
    "Primary",
    "Summer Escape!!",
    "迷宮讃歌",
    "dolce",
    "Dreamer Coaster",
    "Memories",
    "Ringing!",
    "Message",
    "パレードはいつも",
    "ヒロインズ☆ランウェイ",
    "Free Flight",
    "Anniversary",
    "Dears",
    "Departure",
    "Hoshizora Monologue",
    "ひとひらだけ",
    "結び葉"
]

[liella.season_1_singles]
name = "Season 1 Singles"
is_custom = false
songs = [
    "START!! True dreams",
    "だから僕らは鳴らすんだ！",
    "未来は風のように",
    "この街でいまキミと",
    "未来予報ハレルヤ！",
    "Tiny Stars",
    "GOING UP",
    "1.2.3！",
    "常夏☆サンシャイン",
    "Wish Song",
    "バイバイしちゃえば！？",
    "瞬きの先へ",
    "Departure",
    "Day1",
    "Dream Rainbow",
    "Primary"
]

[liella.season_2_singles]
name = "Season 2 Singles"
is_custom = false
songs = [
    "WE WILL!!",
    "スター宣言",
    "追いかける夢の先で",
    "水しぶきのサイン",
    "Welcome to 僕らのセカイ",
    "Go!! リスタート",
    "色づいて透明",
    "揺らぐわ",
    "ビタミンSUMMER！",
    "Chance Day, Chance Way！",
    "ユートピアマジック",
    "POP TALKING",
    "Sing！Shine！Smile！",
    "未来の音が聴こえる",
    "TO BE CONTINUED",
    "名前呼びあうように",
    "Butterfly Wing",
    "エーデルシュタイン"
]

[liella.season_3_singles]
name = "Season 3 Singles"
is_custom = false
songs = [
    "Let's be ONE",
    "DAISUKI FULL POWER",
    "青春HOPPERS",
    "Within a Dream",
    "Bubble Rise",
    "Special Color",
    "いつものピースサイン",
    "ファイティングコール",
    "絶対的LOVER",
    "Dazzling Game",
    "QUESTION99",
    "真っ赤。",
    "笑顔のPromise",
    "スーパースター!!",
    "君・街・空・星",
    "OPEN THE G☆TE!!!"
]

# Example of potential user-defined custom subgroup
# [liella.custom_subgroups.user_top_10]
# name = "User's Top 10"
# is_custom = true
# creator = "admin"
# songs = [
#     "Starlight Prologue",
#     "Aspire",
#     "Dazzling Game",
#     "真っ赤。",
#     "始まりは君の空",
#     "LiLiA",
#     "Starry Prayer",
#     "Free Flight",
#     "絶対的LOVER",
#     "Aspire"
# ]