# app/seeds/subgroups.toml

[liella.all_songs]
name = "All Songs"
is_custom = false
songs = [
    "始まりは君の空",
    "Dancing Heart La-Pa-Pa-Pa!",
    "Dreaming Energy",
    "私のSymphony",
    "START!! True dreams",
    "だから僕らは鳴らすんだ！",
    "未来は風のように",
    "この街でいまキミと",
    "未来予報ハレルヤ！",
    "Tiny Stars",
    "GOING UP",
    "1.2.3！",
    "心キラララ",
    "常夏☆サンシャイン",
    "Wish Song",
    "バイバイしちゃえば！？",
    "瞬きの先へ",
    "ノンフィクション!!",
    "Starlight Prologue",
    "Day1",
    "Dream Rainbow",
    "Primary",
    "Memories",
    "Anniversary",
    "Message",
    "Ringing!",
    "Oh！レディ・ステディ・ポジティブ",
    "Dears",
    "Departure",
    "ほんのちょっぴり",
    "だいすきのうた",
    "グソクムシのうた",
    "Shooting Voice!!",
    "勇気のカケラ",
    "ヒロインズ☆ランウェイ",
    "リバーブ",
    "HOT PASSION!!",
    "Till Sunrise",
    "探して！Future",
    "クレッシェンドゆ・ら",
    "HAPPY TO DO WA！",
    "Stella!",
    "変わらないすべて",
    "トゥ トゥ トゥ！",
    "What a Wonderful Dream!!",
    "青空を待ってる",
    "水色のSunday",
    "Flyer's High",
    "みてろ！",
    "微熱のワルツ",
    "ユニゾン",
    "WE WILL!!",
    "スター宣言",
    "追いかける夢の先で",
    "水しぶきのサイン",
    "Welcome to 僕らのセカイ",
    "Go!! リスタート",
    "色づいて透明",
    "揺らぐわ",
    "ビタミンSUMMER！",
    "Chance Day, Chance Way！",
    "ユートピアマジック",
    "POP TALKING",
    "Sing！Shine！Smile！",
    "未来の音が聴こえる",
    "TO BE CONTINUED",
    "名前呼びあうように",
    "Dreamer Coaster",
    "Butterfly Wing",
    "エンドレスサーキット",
    "迷宮讃歌",
    "プライム・アドベンチャー",
    "パレードはいつも",
    "エーデルシュタイン",
    "駆けるメリーゴーランド",
    "Time to go",
    "Hoshizora Monologue",
    "Blooming Dance！Dance！",
    "Including you",
    "Second Sparkle",
    "ビギナーズRock!!",
    "ミッドナイトラプソディ",
    "星屑クルージング",
    "君を想う花になる",
    "茜心",
    "ガラスボールリジェクション",
    "Eyeをちょうだい",
    "Starry Prayer",
    "Free Flight",
    "MIRACLE NEW STORY",
    "キラーキューン☆",
    "UNIVERSE!!",
    "Jump Into the New World",
    "オルタネイト",
    "ベロア",
    "Dancing Raspberry",
    "影遊び",
    "不可視なブルー",
    "A Little Love",
    "シェキラ☆☆☆",
    "FANTASTiC",
    "ディストーション",
    "ニュートラル",
    "Jellyfish",
    "全力ライオット",
    "カメリアの囁き",
    "Thank you Good morning",
    "アイコトバ！",
    "Let's be ONE",
    "DAISUKI FULL POWER",
    "青春HOPPERS",
    "Within a Dream",
    "Bubble Rise",
    "Special Color",
    "いつものピースサイン",
    "ファイティングコール",
    "絶対的LOVER",
    "Dazzling Game",
    "QUESTION99",
    "真っ赤。",
    "笑顔のPromise",
    "スーパースター!!",
    "君・街・空・星",
    "dolce",
    "Summer Escape!!",
    "11th moon",
    "ひとひらだけ",
    "結ぶメロディ",
    "あふれる言葉",
    "罪DA・YO・NE",
    "想われマリオネット",
    "ティーンエイジ・ロンリネス",
    "Over Over",
    "Sky Linker",
    "LiLiA",
    "てくてく日和",
    "ワイルドカード",
    "ファンダメンタル",
    "Just woo!!",
    "パステルコラージュ",
    "結び葉",
    "ルカ",
    "Rhythm",
    "Aspire",
    "オレンジのままで",
    "High！モチベーション",
    "OPEN THE G☆TE!!!"
]

[liella.liella_no_uta]
name = "Liella no Uta"
is_custom = false
songs = [
    "Free Flight",
    "Over Over",
    "Sky Linker",
    "Dears",
    "Starry Prayer",
    "Just woo!!",
    "Hoshizora Monologue",
    "グソクムシのうた",
    "ティーンエイジ・ロンリネス",
    "ノンフィクション!!",
    "Departure"
]

[liella.group_songs]
name = "Group Songs"
is_custom = false
songs = [
    "Starlight Prologue",
    "Aspire",
    "Dazzling Game",
    "真っ赤。",
    "始まりは君の空",
    "未来は風のように",
    "ビタミンSUMMER！",
    "Bubble Rise",
    "いつものピースサイン",
    "ノンフィクション!!",
    "Second Sparkle",
    "Special Color",
    "私のSymphony",
    "キラーキューン☆",
    "Tiny Stars",
    "スーパースター!!",
    "START!! True dreams",
    "Wish Song",
    "QUESTION99",
    "OPEN THE G☆TE!!!",
    "揺らぐわ",
    "絶対的LOVER",
    "What a Wonderful Dream!!",
    "常夏☆サンシャイン",
    "Day1",
    "未来予報ハレルヤ！",
    "だから僕らは鳴らすんだ！",
    "Chance Day, Chance Way！",
    "笑顔のPromise",
    "アイコトバ！",
    "WE WILL!!",
    "DAISUKI FULL POWER",
    "シェキラ☆☆☆",
    "Jump Into the New World",
    "UNIVERSE!!",
    "MIRACLE NEW STORY",
    "オレンジのままで",
    "結ぶメロディ",
    "追いかける夢の先で",
    "君・街・空・星",
    "Dream Rainbow",
    "Let's be ONE",
    "探して！Future",
    "FANTASTiC",
    "Shooting Voice!!",
    "ユニゾン",
    "TO BE CONTINUED",
    "1.2.3！",
    "Welcome to 僕らのセカイ",
    "青春HOPPERS",
    "POP TALKING",
    "ファイティングコール",
    "バイバイしちゃえば！？",
    "スター宣言",
    "未来の音が聴こえる",
    "この街でいまキミと",
    "瞬きの先へ",
    "Sing！Shine！Smile！",
    "Go!! リスタート",
    "名前呼びあうように",
    "Dancing Heart La-Pa-Pa-Pa!",
    "水しぶきのサイン",
    "Dreaming Energy",
    "GOING UP",
    "Primary",
    "Within a Dream",
    "Including you",
    "色づいて透明",
    "ユートピアマジック",
    "Departure",
    "プライム・アドベンチャー",
    "トゥ トゥ トゥ！",
    "Time to go"
]

[liella.season_1_singles]
name = "Season 1 Singles"
is_custom = false
songs = [
    "START!! True dreams",
    "だから僕らは鳴らすんだ！",
    "未来は風のように",
    "この街でいまキミと",
    "未来予報ハレルヤ！",
    "Tiny Stars",
    "GOING UP",
    "1.2.3！",
    "常夏☆サンシャイン",
    "Wish Song",
    "バイバイしちゃえば！？",
    "瞬きの先へ",
    "ノンフィクション!!",
    "Day1",
    "Dream Rainbow",
    "Starlight Prologue"
]

[liella.season_2_singles]
name = "Season 2 Singles"
is_custom = false
songs = [
    "WE WILL!!",
    "スター宣言",
    "追いかける夢の先で",
    "水しぶきのサイン",
    "Welcome to 僕らのセカイ",
    "Go!! リスタート",
    "色づいて透明",
    "揺らぐわ",
    "ビタミンSUMMER！",
    "Chance Day, Chance Way！",
    "ユートピアマジック",
    "POP TALKING",
    "Sing！Shine！Smile！",
    "未来の音が聴こえる",
    "TO BE CONTINUED",
    "名前呼びあうように",
    "Butterfly Wing",
    "エーデルシュタイン"
]

[liella.season_3_singles]
name = "Season 3 Singles"
is_custom = false
songs = [
    "Let's be ONE",
    "DAISUKI FULL POWER",
    "青春HOPPERS",
    "Within a Dream",
    "Bubble Rise",
    "Special Color",
    "いつものピースサイン",
    "ファイティングコール",
    "絶対的LOVER",
    "Dazzling Game",
    "QUESTION99",
    "真っ赤。",
    "笑顔のPromise",
    "スーパースター!!",
    "君・街・空・星"
]

[liella.catchu]
name = "CatChu!"
is_custom = false
is_subunit = true
songs = [
    "オルタネイト",
    "影遊び",
    "ディストーション",
    "全力ライオット"
]

[liella.kaleidoscore]
name = "KALEIDOSCORE"
is_custom = false
is_subunit = true
songs = [
    "ベロア",
    "不可視なブルー",
    "ニュートラル",
    "カメリアの囁き"
]

[liella.5syncri5e]
name = "5syncri5e!"
is_custom = false
is_subunit = true
songs = [
    "Dancing Raspberry",
    "A Little Love",
    "Jellyfish",
    "Thank you Good morning"
]

# Example of potential user-defined custom subgroup
# [liella.custom_subgroups.user_top_10]
# name = "User's Top 10"l
# is_custom = true
# creator = "admin"
# songs = [
#     "Starlight Prologue",
#     "Aspire",
#     "Dazzling Game",
#     "真っ赤。",
#     "始まりは君の空",
#     "LiLiA",
#     "Starry Prayer",
#     "Free Flight",
#     "絶対的LOVER",
#     "Aspire"
# ]

# --- aqours section ---

[aqours.all_songs]
name = "All Songs"
songs = ['君のこころは輝いてるかい？', 'Step! ZERO to ONE', 'Aqours☆HEROES', '恋になりたいAQUARIUM', '待ってて愛のうた', '届かない星だとしても', '元気全開DAY! DAY! DAY!', '夜空はなんでも知ってるの？', 'トリコリコPLEASE!!', 'ときめき分類学', 'Strawberry Trapper', 'Guilty Night, Guilty Kiss!', '青空Jumping Heart', 'ハミングフレンド', '決めたよHand in Hand', 'ダイスキだったらダイジョウブ！', 'ユメ語るよりユメ歌おう', 'サンシャインぴっかぴか音頭', '夢で夜空を照らしたい', '未熟DREAMER', 'Pops heartで踊るんだもん！', '空も心も晴れるから', '想いよひとつになれ', 'MIRAI TICKET', 'ジングルベルがとまらない', '聖なる日の祈り', 'Waku-Waku-Week!', 'SELF CONTROL!!', 'Daydream Warrior', 'G線上のシンデレラ', 'スリリング・ワンウェイ', '太陽を追いかけろ！', 'P.S.の向こう側', 'LONELY TUNING', 'Guilty Eyes Fever', 'HAPPY PARTY TRAIN', 'SKY JOURNEY', '少女以上の恋がしたい', '近未来ハッピーエンド', '海岸通りで待ってるよ', 'GALAXY HidE and SeeK', 'INNOCENT BIRD', 'コワレヤスキ', 'Shadow gate to love', 'Landing action Yeah!!', '夏への扉 Never end ver.', '真夏は誰のモノ？', '地元愛♡満タン☆サマーライフ', '夏の終わりの雨音が', '未来の僕らは知ってるよ', '君の瞳を巡る冒険', '勇気はどこに？君の胸に！', '“MY LIST” to you!', 'MY舞☆TONIGHT', 'MIRACLE WAVE', 'Awaken the power', 'CRASH MIND', 'DROPOUT!?', 'One More Sunshine Story', 'WATER BLUE NEW WORLD', 'WONDERFUL STORIES', 'おやすみなさん！', 'in this unstable world', 'Pianoforte Monologue', 'Beginner’s Sailing', 'RED GEM WINK', 'WHITE FIRST LOVE', 'New winding road', 'さかなかなんだか？', 'キセキヒカル', 'サクラバイバイ', '卒業ですね', 'Guilty!? Farewell party', 'ホップ・ステップ・ワーイ！', 'Thank you, FRIENDS!!', 'No.10', 'ハジマリロード', '予測不可能Driving!', 'Marine Border Parasol', '僕らの走ってきた道は…', 'Next SPARKLING!!', '逃走迷走メビウスループ', 'Hop? Stop? Nonstop!', 'Believe again', 'Brightest Melody', 'Over The Next Rainbow', 'Jump up HIGH!!', 'i-n-g, I TRY!!', '冒険Type A, B, C!!', '未体験HORIZON', 'Deep Resonance', 'Dance with Minotaurus', 'KOKORO Magic “A to Z”', 'Wake up, Challenger!!', 'New Romantic Sailors', 'Love Pulsar', 'Phantom Rocket Adventure', 'Braveheart Coaster', 'CHANGELESS', 'コドク・テレポート', 'Amazing Travel DNA', '空中恋愛論', 'メイズセカイ', 'シャゼリア☆キッス☆ダダンダーン', 'Fantastic Departure!', 'Aqours Pirates Desire', 'Never giving up!', 'Dazzling White Town', 'Lonely Snow Planet', 'After The Rain', 'JIMO-AI Dash!', 'PURE PHRASE', 'コットンキャンディえいえいおー！', 'Future flight', 'キモチもユメも一緒だね！', '涙が雪になる前に', 'Misty Frosty Love', 'Party! Party! PaPaPaParty!', 'Perfect SEKAI', 'もっとね！', 'あこがれランララン', 'smile smile ship Start!', '心の羽よ君へ飛んでけ！', '突然GIRL', 'ある日…永遠みたいに！', 'Whistle of Revolution', 'ドラゴンライダーズ', 'Shiny Racers', "We'll get the next dream!!!", 'PHOENIX DANCE', 'メタモルフィズム', 'DREAMY COLOR', 'タテホコツバサ', 'Shooting Star Warrior', 'Deep Sea Cocoon', 'Nameless Love Song', 'OKAWARI Happy life!', 'Love Spiral Tower', '1STAR', 'KU-RU-KU-RU Cruller!', 'SUKI for you, DREAM for you!', '涙×', 'LIVE with a smile!', 'not ALONE not HITORI', 'MOTTO-ZUTTO be with you', 'RUN KAKERU RUN', 'やあ！行雲流水！？', 'GEMSTONE “DE-A-I”', 'なんどだって約束！', 'Paradise Chime', 'Love is all, I sing love is all!', 'ユメ+ミライ＝無限大', '迷冥探偵ヨハネ', 'ナミオトリフレイン', 'BANZAI! digital trippers', 'KA-GA-YA-KI-RA-RI-RA', '水面にピアノ', 'アイコトバ', 'わーいわいわい　わいわいわい！', 'ファボタージュ', 'Pure heart Pure wish', 'センチメンタルレモネード', 'TSUBOMI SEASON', '海空のオーロラ', 'また君に会うんだ', 'SORA, FUJI, SUNSHINE!', 'MABOROSHI wing', '異次元★♥BIGBANG', 'peace piece pizza', 'U-CYU', 'SAKURA-saku KOKORO-saku', '僕らの海でまた会おう', 'Bring the LOVE！', '永久hours', '僕らの旅は終わらない', '愛♡スクリ～ム！', 'ICE LIMIT']
# --- Aqours Subunits ---

[aqours.cyaron]
name = "CYaRon!"
is_custom = false
is_subunit = true
songs = [
    "元気全開DAY! DAY! DAY!",
    "夜空はなんでも知ってるの？",
    "P.S.の向こう側",
    "近未来ハッピーエンド",
    "海岸通りで待ってるよ",
    "サクラバイバイ",
    "Braveheart Coaster",
    "CHANGELESS",
    "コドク・テレポート",
    "Whistle of Revolution",
    "ある日…永遠みたいに！",
    "ドラゴンライダーズ"
]

[aqours.azalea]
name = "AZALEA"
is_custom = false
is_subunit = true
songs = [
    "トリコリコPLEASE!!",
    "ときめき分類学",
    "LONELY TUNING",
    "INNOCENT BIRD",
    "GALAXY HidE and SeeK",
    "卒業ですね",
    "Amazing Travel DNA",
    "空中恋愛論",
    "メイズセカイ",
    "We'll get the next dream!!!",
    "PHOENIX DANCE",
    "メタモルフィズム"
]

[aqours.guilty_kiss]
name = "Guilty Kiss"
is_custom = false
is_subunit = true
songs = [
    "Strawberry Trapper",
    "Guilty Night, Guilty Kiss!",
    "Guilty Eyes Fever",
    "コワレヤスキ",
    "Shadow gate to love",
    "Guilty!? Farewell party",
    "New Romantic Sailors",
    "Love Pulsar",
    "Phantom Rocket Adventure",
    "Shooting Star Warrior",
    "Deep Sea Cocoon",
    "Nameless Love Song"
]

[aqours.saint_snow]
name = "Saint Snow"
is_custom = false
is_subunit = true
songs = [
    "SELF CONTROL!!",
    "CRASH MIND",
    "DROPOUT!?",
    "Believe again",
    "Over The Next Rainbow",
    "Dazzling White Town",
    "Lonely Snow Planet",
    "After The Rain"
]

# --- Liella Member Solos & Rivals ---

[liella.kanon_solos]
name = "Kanon Solos"
is_custom = false
is_subunit = true
songs = [
    "青空を待ってる",
    "Free Flight",
    "Over Over",
    "ほんのちょっぴり",
    "心キラララ",
    "だいすきのうた"
]

[liella.keke_solos]
name = "Keke Solos"
is_custom = false
is_subunit = true
songs = [
   "Oh！レディ・ステディ・ポジティブ",
   "ファンダメンタル",
   "星屑クルージング",
   "水色のSunday"
]

[liella.chisato_solos]
name = "Chisato Solos"
is_custom = false
is_subunit = true
songs = [
    "勇気のカケラ",
    "Flyer’s High",
    "君を想う花になる"
]

[liella.sumire_solos]
name = "Sumire Solos"
is_custom = false
is_subunit = true
songs = [
    "ヒロインズ☆ランウェイ",
    "みてろ！",
    "Starry Prayer",
    "Just woo!!",
    "グソクムシのうた"
]

[liella.ren_solos]
name = "Ren Solos"
is_custom = false
is_subunit = true
songs = [
    "結び葉",
    "微熱のワルツ",
    "リバーブ",
    "ミッドナイトラプソディ"
]

[liella.kinako_solos]
name = "Kinako Solos"
is_custom = false
is_subunit = true
songs = [
    "ビギナーズRock!!",
    "あふれる言葉",
    "てくてく日和"
]

[liella.mei_solos]
name = "Mei Solos"
is_custom = false
is_subunit = true
songs = [
    "茜心",
    "Sky Linker"
]

[liella.shiki_solos]
name = "Shiki Solos"
is_custom = false
is_subunit = true
songs = [
    "ガラスボールリジェクション",
    "LiLiA"
]

[liella.natsumi_solos]
name = "Natsumi Solos"
is_custom = false
is_subunit = true
songs = [
    "Eyeをちょうだい",
    "パステルコラージュ"
]

[liella.wien_solos]
name = "Wien Solos"
is_custom = false
is_subunit = true
songs = [
    "エーデルシュタイン",
    "ルカ",
    "dolce",
    "Butterfly Wing"
]

[liella.tomari_solos]
name = "Tomari Solos"
is_custom = false
is_subunit = true
songs = [
    "ワイルドカード"
]

[liella.sunny_passion]
name = "Sunny Passion"
is_custom = false
is_subunit = true
songs = [
    "HOT PASSION!!",
    "Till Sunrise"
]

[liella.all_solos]
name = "All Solos"
is_custom = false
is_subunit = true
songs = [
    # Kanon
    "青空を待ってる", "Free Flight", "Over Over", "ほんのちょっぴり", "心キラララ", "だいすきのうた",
    # Keke
    "Oh！レディ・ステディ・ポジティブ", "ファンダメンタル", "星屑クルージング", "水色のSunday",
    # Chisato
    "勇気のカケラ", "Flyer’s High", "君を想う花になる",
    # Sumire
    "ヒロインズ☆ランウェイ", "みてろ！", "Starry Prayer", "Just woo!!", "グソクムシのうた",
    # Ren
    "結び葉", "微熱のワルツ", "リバーブ", "ミッドナイトラプソディ",
    # Kinako
    "ビギナーズRock!!", "あふれる言葉", "てくてく日和",
    # Mei
    "茜心", "Sky Linker",
    # Shiki
    "ガラスボールリジェクション", "LiLiA",
    # Natsumi
    "Eyeをちょうだい", "パステルコラージュ",
    # Wien
    "エーデルシュタイン", "ルカ", "dolce", "Butterfly Wing",
    # Tomari
    "ワイルドカード"
]